---
- name: Starting docker service
  hosts: infra
  become: yes
  become_user: dev
  tasks:
  - name: Starting docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Create a volume
    docker_volume:
      name: bambooVolume
      
  #- name: pull image
  #  command: docker pull jrrickerson/capstone-bamboo

  #- name: switch user to dev
  #  command: sudo su dev 
  - name: run bamboo from image on docker volume
    command: docker run --group-add $(getent group docker | cut -d ":" -f 3) -v /var/run/docker.sock:/var/run/docker.sock -v bambooVolume:/var/bamboo/bamboo-home --name="bamboo" --init -d -p 54663:54663 -p 8085:8085 jrrickerson/capstone-bamboo
