# Ansible playbook AWS - install docker (2021)
---
- name: "AWS - Install docker"
  hosts: all
  become: yes
  vars_files:
    - vars/default.yaml
  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    
  - name: Install required system packages for Docker
    apt: name={{ docker_required_packages }} state=latest update_cache=yes
  
  - name: Add Docker GPG key
    apt_key:
      url: "{{ docker_gpg_url }}"
      state: present
    
  - name: Add Docker repository
    apt_repository:
      repo: "{{ docker_repo }}"
      state: present
   
  - name: Install Docker
    apt: name={{ docker_packges }} state=latest update_cache=yes
    
  - name: Install Python Docker module
    pip:
      name: docker
    
  - name: Add adminstrator to docker group
    user:
      name: "{{ admin_user }}"
      groups: docker
      append: yes

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true
  
  - name: change docker socket file permissions
    command: sudo chmod 771 /var/run/docker.sock
  
    #-name: Install Docker Compose
  # get_url:
  #    url: "{{ docker_compose_url }}"
  #    dest: /usr/local/bin/docker-compose
  #    mode: '755'
     